INSERT INTO Rodzaje_pracownikow VALUES
 ('Pielegniarka'),
 ('Lekarz'),
 ('Lekarz specjalista'),
 ('Ginekolog'),
 ('Chirurg'),
 ('Dyrektor'),
 ('Dyrektor personalny'),
 ('Pielegniarka oddzialowa'),
 ('Dostawca'),
 ('Lekarz rodzinny'),
 ('Pediatra'),
 ('Anestezjolog'),
 ('Farmaceuta'),
 ('Recepcjonista'),
 ('Dyrektor wykonawczy'),
 ('Asystent'),
 ('Student'),
 ('Stazysta'),
 ('Praktykant'),
 ('Manager'),
 ('Sprzatacz'),
 ('Informatyk'),
 ('Kierownik'),
 ('Ochroniarz'),
 ('Recepcjolistka'),
 ('Zarzadca'),
 ('Dyrektor medyczny'),
 ('Sprzataczka');
 
